//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geodeta.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Line = new HashSet<Line>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateMod { get; set; }
        public bool IsNewVersion { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Line> Line { get; set; }
    }
}
