//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geodeta.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListOfPoints
    {
        public int ID { get; set; }
        public int PointId { get; set; }
        public int LineId { get; set; }
    
        public virtual Line Line { get; set; }
        public virtual Point Point { get; set; }
    }
}
