//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geodeta.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public Note()
        {
            this.Line = new HashSet<Line>();
            this.Point = new HashSet<Point>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string ContentNote { get; set; }
    
        public virtual ICollection<Line> Line { get; set; }
        public virtual ICollection<Point> Point { get; set; }
    }
}
